export const LOCATORS = {

    //common locators
    ADMIN: "//div[contains(text(),'Admin')]",
    MODULEMANAGEMENT:"//a[text()='Module Management']",
    ACTIVEUSERS:"//a[text()='Active Users']",
    ACCOUNT: "//div[contains(text(),'Account')]",
    LOGOUT: "//a[text()='Logout']",
    MODULE_SELECTION: "//a[text()='Module Selection']",
    EXPLORE: "//div[text()='Explore']",
    MAPS: "//a[text()='Maps']",

    //module management
    VERIFYMODULETEXT:"//div[text()='Please select a module']",
    MODULESEARCHBOX:"//div[@id='wrapped-datagrid']/descendant::input[@aria-label='Search in data grid']",
    MODULETXT:"//tr[@aria-rowindex='1']//td[@aria-colindex='2']",

    //active users
    ACTIVEUSERLIST:"//div[@class='ActiveUsersstyles__User-sc-v18f9q-0 bUbVxy']",

    //login locators
    LOGIN_USERNAME: "//input[@data-testid='textField-username']",
    LOGIN_PASSWORD: "//input[@data-testid='textField-password']",
    LOGIN_BUTTON: "//button[@data-testid='button-login']",

    //module selection locators
    MODULE_DROPDOWN: "//div[@class=' css-e56m7-control']",
    MODULE_NAME: "//div[@class=' css-1hwfws3']",
    MODULENAMEFROMADMIN:"(//div[@class=' css-1hwfws3'])[2]",
    MODULE_SELECT: "//div[@id='react-select-2-option-4']",
    MODULESELECTFROMADMIN:"//div[@id='react-select-3-option-4']",
    UPDATEDMODULE:"//div[text()='AH - Demo - Anoka-Hennepin']",

    //layers
    STUDENTS_DATASET_THREEDOTICON: "(//i[@class='dx-icon dx-icon-overflow'])[1]",
    STUDENTS_DATASET_ENABLECLUSTERING: "//div[@title='Enable Clustering']",
    STUDENTS_DATASET_DISABLECLUSTERING: "//div[@title='Disable Clustering']",
    STUDENTS_DATASET_ENABLECLUSTERING_VERIFY:"//img[@src='https://maps.gstatic.com/mapfiles/transparent.png']",

    //create map locators
    MAPNAME: "//span[@class='Mapsstyles__OpenedViewName-sc-1q92y9g-11 xeajc']",
    DATASET_DROPDOWN: "(//div[@class='Layersstyles__RowHolder-sc-1f7sm1t-1 hcxiac']//input[@class='dx-texteditor-input'])[1]",
    STUDENTS_DATASET: "//div[contains(text(),'Students (Current)')]",
    STUDENT_DATASET_CHECKBOX_ICON: "//span[@class='dx-checkbox-icon']",
    STUDENT_DATASET_CHECKBOX: "(//div[@role='checkbox'])[2]",
    OVERLAYS_DROPDOWN: "(//div[@class='Layersstyles__RowHolder-sc-1f7sm1t-1 hcxiac']//input[@class='dx-texteditor-input'])[2]",
    ELEMBUILD_OVERLAYS: "//div[text()='Elementary Buildings']",
    ELEMBUILD_OVERLAYS_CHECKBOX_ICON: "(//span[@class='dx-checkbox-icon'])[4]",
    ELEMBUILD_OVERLAYS_CHECKBOX: "(//div[@role='checkbox'])[4]",
    HIGHBUILD_OVERLAYS: "//div[contains(text(),'High Buildings')]",
    HIGHBUILD_OVERLAYS_CHECKBOX_ICON: "(//span[@class='dx-checkbox-icon'])[5]",
    HIGHBUILD_OVERLAYS_CHECKBOX: "(//div[@role='checkbox'])[5]",
    MIDBUILD_OVERLAYS: "//div[contains(text(),'Middle Buildings')]",
    MIDBUILD_OVERLAYS_CHECKBOX_ICON: "(//span[@class='dx-checkbox-icon'])[6]",
    MIDBUILD_OVERLAYS_CHECKBOX: "(//div[@role='checkbox'])[6]",
    ELEMSCHOOLS_OVERLAYS: "//div[contains(text(),'Elementary Schools')]",
    ELEMSCHOOLS_OVERLAYS_CHECKBOX_ICON: "(//span[@class='dx-checkbox-icon'])[4]",
    ELEMSCHOOLS_OVERLAYS_CHECKBOX: "(//div[@role='checkbox'])[4]",
    HIGHSCHOOLS_OVERLAYS: "//div[contains(text(),'High Schools')]",
    HIGHSCHOOLS_OVERLAYS_CHECKBOX_ICON: "(//span[@class='dx-checkbox-icon'])[5]",
    HIGHSCHOOLS_OVERLAYS_CHECKBOX: "(//div[@role='checkbox'])[5]",
    MIDSCHOOLS_OVERLAYS: "//div[contains(text(),'Middle Schools')]",
    MIDSCHOOLS_OVERLAYS_CHECKBOX_ICON: "(//span[@class='dx-checkbox-icon'])[6]",
    MIDSCHOOLS_OVERLAYS_CHECKBOX: "(//div[@role='checkbox'])[6]",
    SAVE_MAP_ICON: "(//div[@class='rightsidebutton dx-button dx-button-normal dx-button-mode-contained dx-widget'])[1]",
    MAPNAME_TXTBX: "(//input[@class='dx-texteditor-input'])[11]",
    PERMISSION_CHKBX: "(//div[@class='dx-widget dx-collection']//div[@role='radio'])[2]",
    SAVEMAP_BUTTON: "//button[text()='Save']",
    SPATIALFILTERICON: "(//div[@title='Overlay Spatial Filter']//div[@class='dx-button-content'])[2]",
    INCLUDESPATIALFILTER: "//div[contains(text(),'Include')]",
    EXCLUDESPATIALFILTER: "//div[contains(text(),'Exclude')]",
    OFFSPATIALFILTER: "//div[contains(text(),'Off')]",
    OPENMAP_ICON: "//div[@title='Open']",
    OPENMAP_BTN: "//button[text()='Open']",
    OPENMAPFROMLIST: "(//div[@role='option']//div[@class='item'])[1]",
    EXPORTMAPICON: "//div[@title='Export']",
    EXPORTTOPNG: "//span[@class='dx-checkbox-text'][text()=' Map (.png)']",
    EXPORTTOMAPANDDETAILS: "//span[@class='dx-checkbox-text'][text()=' Map and Details (.xls)']",
    EXPORTTODATATABLE: "//span[@class='dx-checkbox-text'][text()=' Data Table (.xls)']",
    EXPORTMAPDOWNLOAD: "//button[text()='Download']",
    SHOWGRIDICON: "//div[@title='Show Grid'][@role='button']",
    GRIDDISTRICTNAME: "//div[text()='District  Name']",
    SHOWANALYTICSICON: "//div[@title='Show Analytics'][@role='button']",
    SHOWMAPICON: "//div[@title='Show Map'][@role='button']",
    STREETMAPBUTTON: "//button[@title='Show street map']",
    DRAWINGTOOLICON: "//div[@title='Drawing Tools'][@role='button']",
    DRAWINGTOOLMENUBAR: "(//div[@class='gmnoprint'][@role='menubar'])[2]",
    RELOADICON: "//div[@title='Reload']",
    ROUTINGTOOLSICON:"//div[@title='Routing Tools']",
    DRAWROUTEBUTTON:"//span[text()='Draw Route']",
    ROUTEVIAWAYPOINTS:"//span[text()='Route via Waypoints']",
    HIGHLIGHTACTIVESPATIALFILTERSHAPES:"//div[@title='Highlight Active Spatial Filter Shapes']",

    //indicators
    INDICATORSTAB: "//li[text()='Indicators']",
    INDICATORCAPACITYVAL: "//tr[@aria-rowindex='1']//td[@aria-colindex='1']",
    INDICATOROVERUNDERVAL: "//tr[@aria-rowindex='1']//td[@aria-colindex='2']",
    INDICATORPERCENTVAL: "//tr[@aria-rowindex='1']//td[@aria-colindex='3']",
    CAPACITYHEADER: "//div[text()='Capacity'][@role='presentation']",
    SORTASCENDING: "//span[text()='Sort Ascending']",
    SORTDESCENDING: "//span[text()='Sort Descending']",
    CLEARINDICATORSORTING: "//span[text()='Clear Sorting']",
    OVERUNDERHEADER: "//div[text()='Over/Under'][@role='presentation']",
    PERCENTHEADER: "//div[text()='% Capacity'][@role='presentation']",

    //explore map locators
    OPEN_SELECTED: "//tr[@aria-rowindex='1']//span[text()='Test Automation Map']",
    DELETE_SELECTED: "//span[text()='Delete Selected']",
    SEARCH_MAP_TXTBX: "//input[@class='dx-texteditor-input']",
    CREATE_MAP: "//button[@class='Buttonstyles__StyledButton-sc-lzxiep-0 fqGswk']",
    MAPNAME_CHECKBOX: "(//span[@class='dx-checkbox-icon'])[2]",
    FIRSTROW_MAPNAME: "(//tr[@aria-rowindex='1']//td)[2]",
    DELETE_SELECTED_MAP_BUTTON: "//span[text()='Delete Selected']",
    DELETE_MAP_YES: "//span[text()='Yes']",
    SELECT_ALL_MAP_CHECKBOX: "//td[@aria-label='Select all']//div[@role='checkbox']",
    SORT_BY_NAME: "//div[text()='Name']",
    SORT_BY_DESC: "//div[text()='Description']",
    SORT_BY_CREATEDON: "//div[text()='Created On']",
    SORT_BY_CREATEDBY: "//div[text()='Created By']",
    SORT_BY_LAST_UPDATED: "//div[text()='Last Updated']",
    CLEARMAPSORTING: "//span[text()='Clear Sorting']",

    //filters tab
    FILTERS_TAB: "//li[text()='Filters']",
    DATASET_FILTER_ICON: "(//div[@class='filterButtton dx-button dx-button-normal dx-button-mode-contained dx-widget'])[1]",
    OVERLAYS_FILTER_ICON: "(//div[@class='filterButtton dx-button dx-button-normal dx-button-mode-contained dx-widget'])[2]",
    FILTER_SEARCHBOX: "(//input[@class='dx-texteditor-input'][@aria-label='Search in data grid'])[2]",
    SELECTEDFILTER_CHECKBOX: ".dx-treelist-icon-container > .dx-select-checkbox > .dx-checkbox-container > .dx-checkbox-icon",
    GRADELEVEL_CHECKBOX: "(//div[@class='dx-select-checkbox dx-treelist-checkbox-size dx-show-invalid-badge dx-checkbox dx-widget']/following::span[@class='dx-checkbox-icon'])[1]",
    ASIAN_CHECKBOX: "//div[@class='dx-show-invalid-badge dx-checkbox dx-checkbox-has-text dx-widget']//span[text()='Asian']",
    MALE_CHECKBOX: ":nth-child(2) > .dx-show-invalid-badge > .dx-checkbox-container > .dx-checkbox-icon",
    SCHOOLTYPE_CHECKBOX1: "(//div[@class='dx-show-invalid-badge dx-checkbox dx-checkbox-has-text dx-widget']//span[@class='dx-checkbox-icon'])[2]",
    SCHOOLTYPE_CHECKBOX2: "(//div[@class='dx-show-invalid-badge dx-checkbox dx-checkbox-has-text dx-widget']//span[@class='dx-checkbox-icon'])[4]",
    FILTER_APPLY_BUTTON: ".GdpPR",
    DISABLE_FILTER_CHECKBOX: ".AttributeFiltersstyles__ItemHolder-sc-11xu74x-2 > .dx-show-invalid-badge > .dx-checkbox-container > .dx-checkbox-icon",
    REMOVEFILTER_BUTTON1: "//div[@title='Remove item']",
    GRADE_01_CHECKBOX: "(//span[@class='dx-checkbox-icon'])[8]",
    GRADE_02_CHECKBOX: "(//span[@class='dx-checkbox-icon'])[9]",
    GRADE_03_CHECKBOX: "(//span[@class='dx-checkbox-icon'])[10]",

    //stats tab
    STATS_TAB: "#react-tabs-8",
    STATS_DROPDOWN: ":nth-child(2) > .css-2b097c-container > .css-e56m7-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer",
    STATSDATA1: "//div[text()='Select...']/following::input[1]",
    STATSDATA1_VALUE: "//div[@class=' css-i0syzg-menu']",
    STATS_STUDENTSDATA: "//div[@class='Statsstyles__RightHolderFlexRow-sc-1slzopn-6 dRZdBX']",
    SELECT_ADDITIONAL_DATA_BUTTON: "//button[text()='Select Additional Data']",
    SEARCH_DATA: "(//div[@class='dx-icon dx-icon-search']/following::input[@class='dx-texteditor-input'])[1]",
    ADDDATA_APPLY_BUTTON: "(//button[text()='Apply'])[2]",
    ADDDATA_CHECKBOX: "(//span[@class='dx-checkbox-icon'])[6]",
    STATS_ADDDATA_DROPDOWN: "(//div[@class=' css-1hwfws3'])[2]",
    STATS_ADDDATA_VALUE: "//div[@class=' css-i0syzg-menu']",
    ADDDATA_CHECKBOX1: ".dx-select-checkbox > .dx-checkbox-container > .dx-checkbox-icon",
    STATS_MIDDLESCHOOL_COUNT: "((//tr[@class='dx-row dx-data-row'])[2]/descendant::td)[2]",

}

